language: clojure
lein: 2.8.1
script:
  - lein source-deps :prefix-exclusions "[\"classlojure\"]"
  - lein with-profile +plugin.mranderson/config test
  - lein with-profile +1.8,+plugin.mranderson/config test
  - lein with-profile +1.9,+plugin.mranderson/config test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/69f4ae3e4e772d83a1b1
