language: clojure
script:
  - lein2 source-deps :prefix-exclusions "[\"classlojure\"]"
  - lein2 with-profile +1.5,+plugin.mranderson/config test
  - lein2 with-profile +1.6,+plugin.mranderson/config test
  - lein2 with-profile +1.7,+plugin.mranderson/config test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/69f4ae3e4e772d83a1b1
