version: 2

jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein source-deps :prefix-exclusions "[\"classlojure\"]"
      - run: lein with-profile +plugin.mranderson/config test
      - run: lein with-profile +1.9,+plugin.mranderson/config test

      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein

          key: clj-deps-{{ checksum "project.clj" }}
        
workflows:
  version: 2
  test:
    jobs:
      - test
